# Ossiaco JSON Converter Library
# 
# Copyright (C) 2018 Ossiaco
# 
# Licensed under the MIT license ("the license"); you may not use this file
# except in compliance with the license. The license can be found in the root
# directory of this project, or at
# 
# http://opensource.org/licenses/MIT
#
# This travis.yml borrows heavily from that written by Louis Dionne for boostorg/hana

language: cpp
os: linux
dist: trusty
sudo: false

branches:
  except:
  - /appveyor.*/

matrix:
  include:
    # Comment these out for now to allow easy initial troubleshooting
    # Clang 4.0
    #- env: COMPILER=clang++-4.0 ENABLE_MEMCHECK=true
    #  addons: { apt: { packages: ["clang-4.0", "valgrind"], sources: ["ubuntu-toolchain-r-test", "llvm-toolchain-trusty-4.0"] } }

    # Clang 5.0
    #- env: COMPILER=clang++-5.0 ENABLE_MEMCHECK=true
    #  addons: &defaults { apt: { packages: ["clang-5.0", "valgrind"], sources: ["ubuntu-toolchain-r-test", "llvm-toolchain-trusty-5.0"] } }
    
    # GCC 7
    - env: COMPILER=g++-7 ENABLE_MEMCHECK
      addons: { apt: { packages: ["g++-7", "valgrind"], sources: ["ubuntu-toolchain-r-test"] } }

install:
  - DEPS_DIR="${HOME}/deps"
  - mkdir -p ${DEPS_DIR} && cd ${DEPS_DIR}

  - travis_retry wget -q https://dl.bintray.com/boostorg/release/1.67.0/source/boost_1_67_0.tar.gz
  - tar xf boost_1_67_0.tar.gz

  # Get vcpkg with proper version of range-v3 and also rapidjson with install targets
  # We "steal" the version of cmake downloaded with vcpkg to avoid pulling it twice
  - |
    if [[ ! -d vcpkg ]]; then
      git clone https://github.com/Microsoft/vcpkg.git && cd vcpkg
      git checkout 4d28651
      ./bootstrap-vcpkg.sh
    fi
  - ./vcpkg/vcpkg install date range-v3 rapidjson

  - alias cmake="$(find ./vcpkg/downloads/tools/ -regextype sed -regex ".*/bin/cmake")""
  - cmake --version

  - cd "${TRAVIS_BUILD_DIR}"
  - mkdir build && cd build
  - cmake --warn-uninitialized -DCMAKE_CXX_COMPILER="${COMPILER}" -DBOOST_ROOT="${HOME}/deps/boost_1_67_0" -DCMAKE_TOOLCHAIN_FILE="${HOME}/deps/vcpkg/scripts/buildsystems/vcpkg.cmake" -DOSSIACO_CONVERTER_TESTS=ON ../

script:
  - make -j4
  - ctest --output-on-failure
  - |
    if [[ "${ENABLE_MEMCHECK}" == "true" ]]; then
      valgrind ctest
    fi

cache:
  directories:
    - "${DEPS_DIR}/vcpkg"

notifications:
  email: false