# Ossiaco JSON Converter Library
# 
# Copyright (C) 2018 Ossiaco
# 
# Licensed under the MIT license ("the license"); you may not use this file
# except in compliance with the license. The license can be found in the root
# directory of this project, or at
# 
# http://opensource.org/licenses/MIT
#
# This travis.yml borrows heavily from that written by Louis Dionne for boostorg/hana

language: cpp
os: linux
dist: trusty
sudo: false

branches:
  except:
  - /appveyor.*/

matrix:
  include:
    # GCC 7
    - env: _CC=gcc-7 _CXX=g++-7
      addons: { apt: { packages: ["g++-7", "valgrind"], sources: ["ubuntu-toolchain-r-test"] } }

    # GCC 8
    - env: _CC=gcc-8 _CXX=g++-8
      addons: { apt: { packages: ["g++-8", "valgrind"], sources: ["ubuntu-toolchain-r-test"] } }
    
    # Clang 5
    - env: _CC=clang-5.0 _CXX=clang++-5.0
      addons: { apt: { packages: ["clang-5.0", "valgrind", "libstdc++-7-dev"], sources: ["ubuntu-toolchain-r-test", "llvm-toolchain-trusty-5.0"] } }

    # Clang 6
    - env: COMPILER=clang++-6.0
      addons: { apt: { packages: ["clang-6.0", "valgrind", "libstdc++-7-dev"], sources: ["ubuntu-toolchain-r-test", "llvm-toolchain-trusty-6.0"] } }

install:
  - |
    export CC=${_CC}
    export CXX=${_CXX}
    ${CC} --version
    ${CXX} --version

  - DEPS_DIR="${HOME}/deps"; mkdir -p ${DEPS_DIR} && cd ${DEPS_DIR}

  - |
    sudo pip install conan
    conan --version
    conan remote add bincrafters https://api.bintray.com/conan/bincrafters/public-conan
  
  - |
    cd ${DEPS_DIR}
    echo \
      '[requires]
      boost/1.68.0@conan/stable
      date/2.4.1@bincrafters/stable
      range-v3/0.4.0@ericniebler/stable
      rapidjson/1.1.0@bincrafters/stable

      [generators]
      cmake_paths

      [options]
      Boost:header_only=True
      ' > conanfile.txt

    cat conanfile.txt
    conan install . -s compiler.libcxx=libstdc++11 --build missing

  - |
    CMAKE_URL="https://cmake.org/files/v3.10/cmake-3.10.0-Linux-x86_64.tar.gz"
    mkdir cmake && travis_retry wget --no-check-certificate --quiet -O - ${CMAKE_URL} | tar --strip-components=1 -xz -C cmake
    export PATH=${DEPS_DIR}/cmake/bin:${PATH}
    cmake --version

script:
  - cd "${TRAVIS_BUILD_DIR}"
  - mkdir build && cd build
  - cmake --warn-uninitialized -DCMAKE_TOOLCHAIN_FILE="${DEPS_DIR}/conan_paths.cmake"  -DOSSIACO_CONVERTER_EXAMPLES=ON -DOSSIACO_CONVERTER_TESTS=ON ../  
  - make -j4
  - ctest --output-on-failure
  - valgrind ctest

notifications:
  email: false