# Ossiaco JSON Converter Library
# 
# Copyright (C) 2018 Ossiaco
# 
# Licensed under the MIT license ("the license"); you may not use this file
# except in compliance with the license. The license can be found in the root
# directory of this project, or at
# 
# http://opensource.org/licenses/MIT

version: '{build}'

shallow_clone: true

os:
  - Visual Studio 2017

platform:
  - x64

configuration:
  - Debug
  - Release

environment:
  VCPKG_DEFAULT_TRIPLET: x64-windows

cache:
  - c:/tools/vcpkg/installed
  - c:/project/deps/boost_1_67_0

install:
  - cd c:/project
  - mkdir deps\ && cd deps\
  - appveyor DownloadFile https://dl.bintray.com/boostorg/release/1.67.0/source/boost_1_67_0.7z
  - 7z x boost_1_67_0.7z > nul
  - vcpkg install range-v3 rapidjson date
  
build_script:
  - call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat"
  - cd c:/projects/converter
  - mkdir build\ && cd build\
  - cmake --warn-uninitialized -G"Visual Studio 15 2017 Win64" -DCMAKE_BUILD_TYPE=%CONFIGURATION% -DBOOST_ROOT=c:/project/deps/boost_1_67_0 -DCMAKE_TOOLCHAIN_FILE=c:/tools/vcpkg/scripts/buildsystems/vcpkg.cmake -DVCPKG_TARGET_TRIPLET=x64-windows -DOSSIACO_CONVERTER_TESTS=ON -DOSSIACO_WCHAR_UNICODE=ON ..\
  - cmake --build . -- /m

test_script:
  - ctest -C %CONFIGURATION% --output-on-failure