# Ossiaco JSON Converter Library
# 
# Copyright (C) 2018 Ossiaco
# 
# Licensed under the MIT license ("the license"); you may not use this file
# except in compliance with the license. The license can be found in the root
# directory of this project, or at
# 
# http://opensource.org/licenses/MIT

version: '{build}'

shallow_clone: true

os:
  - Visual Studio 2017
  - Visual Studio 2017 Preview

platform:
  - x86
  - x64

configuration: 
  - Debug
  - Release

branches:
  except:
    - /travis.*/

skip_commits:
  files:
    - '*.md'
    - .travis.yml


matrix:
  allow_failures:
    - os: Visual Studio 2017 Preview

environment:
  VCPKG_DEFAULT_TRIPLET: '%PLATFORM%-windows'

cache:
  - c:/tools/vcpkg/installed

install:
  - mkdir c:\project\deps\ && cd c:\project\deps\
  - appveyor DownloadFile https://dl.bintray.com/boostorg/release/1.67.0/source/boost_1_67_0.7z
  - 7z x boost_1_67_0.7z > nul
  - vcpkg install range-v3 rapidjson date
  - cd c:/projects/converter
  - mkdir build && cd build
  - call cmake --warn-uninitialized -G"Visual Studio 15 2017 Win64" -DCMAKE_BUILD_TYPE=%CONFIGURATION% -DBOOST_ROOT=c:/project/deps/boost_1_67_0 -DCMAKE_TOOLCHAIN_FILE=c:/tools/vcpkg/scripts/buildsystems/vcpkg.cmake -DVCPKG_TARGET_TRIPLET=%VCPKG_DEFAULT_TRIPLET% -DOSSIACO_CONVERTER_EXAMPLES=ON -DOSSIACO_CONVERTER_TESTS=ON -DOSSIACO_WCHAR_UNICODE=ON ..\

build:
  project: c:/projects/converter/build/ALL_BUILD.vcxproj
  parallel: true
  verbosity: minimal

test_script:
  - ctest --ouput-on-failure -C %CONFIGURATION%
