# Ossiaco JSON Converter Library
#
# Copyright (C) 2018-2019 Ossiaco
#
# Licensed under the MIT license ("the license"); you may not use this file
# except in compliance with the license. The license can be found in the root
# directory of this project, or at
#
# http://opensource.org/licenses/MIT

resources:
  repositories:
  - repository: AzureTemplates
    type: git
    name: AzureTemplates
    ref: refs/tags/alpha-8

trigger:
  branches:
    include:
    - feature/*
    - master
  paths:
    exclude:
    - README.md

variables:
  BOOST_DEFAULT_VERSION: "1.69.0"
  BOOST_VERSION: $(BOOST_DEFAULT_VERSION)
  CONAN_OPTS: -o boost:header_only=True
  CMAKE_OPTS: -DOSSIACO_CONVERTER_TESTS=1 -DOSSIACO_CONVERTER_EXAMPLES=1 -DCMAKE_TOOLCHAIN_FILE=conan_paths.cmake
  EXTRA_CMAKE_OPTS:

jobs:
- template: job-template.yml
  parameters:
    name: VS2019
    vmImage: 'windows-2019'

- template: job-template.yml
  parameters:
    name: VS2017
    vmImage: 'vs2017-win2016'
    matrix:
      vs2017-rel:
        BUILD_TYPE: Release

- template: job-template.yml
  parameters:
    name: Mac
    vmImage: 'macOS-10.14'

- template: job-template.yml
  parameters:
    name: Linux
    vmImage: 'ubuntu 16.04'
    variables:
      BUILD_TYPE: Release
    matrix:
      gcc7-rel:
        CXX: g++-7

      gcc8-dbg:
        CXX: g++-8
        BUILD_TYPE: Debug
        ENABLE_MEMCHECK: 1

      gcc8-rel:
        CXX: g++-8
        BUILD_TYPE: Release

      gcc8-rel-boost-1_67:
        CXX: g++-8
        BOOST_VERSION: "1.67.0"

      gcc8-rel-boost-1_68:
        CXX: g++-8
        BOOST_VERSION: "1.68.0"

      clang4-rel:
        CXX: clang++-4.0

      clang5-rel:
        CXX: clang++-5.0

      clang6-rel:
        CXX: clang++-6.0

#       # clang7-dbg:
#       #   CXX: clang++-7
#       #   BUILD_TYPE: Debug
#       #   ENABLE_MEMCHECK: 1

#       # clang7-rel:
#       #   CXX: clang++-7

      clang8-dbg:
        CXX: clang++-8
        BUILD_TYPE: Debug
        ENABLE_MEMCHECK: 1

      clang8-rel:
        CXX: clang++-8

      clang8-ubasan:
        BUILD_TYPE: RelWithDebInfo
        CXX: clang++-8
        EXTRA_CMAKE_OPTS: "-DOSSIACO_CONVERTER_UBASAN=1"